name: RocketGamesPatchNotes
title: Rocket Patch Notes
description: >-
    This page contains the patch notes and descriptions for the Rocket Games Packages.
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
logo: "favicon.png"