name: RocketGamesPatchNotes
title: Rocket Patch Notes
description: >-
    This page contains the patch notes and descriptions for the Rocket Games Packages.
remote_theme: just-the-docs/just-the-docs
color_scheme: dark